<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\TagBites.ComponentModel.Composition\TagBites.ComponentModel.Composition.csproj" />
    <ProjectReference Include="..\TagBites.ComponentModel.Composition.Tests.Plugin\TagBites.ComponentModel.Composition.Tests.Plugin.csproj" />
  </ItemGroup>

</Project>
