<Project Sdk="Microsoft.NET.Sdk">

  <!-- Targets -->
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>TagBites</RootNamespace>
  </PropertyGroup>

  <!-- Build -->
  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <!-- README -->
  <ItemGroup>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Composition" Version="4.6.0" />
  </ItemGroup>

</Project>
